version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak-server
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
    command: start-dev