version: '3.7'

networks:
  mysql-net:
    driver: bridge

services:
  mysql:
    image: mysql
    container_name: mysql
    networks:
      - mysql-net
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - mysql-net
    ports:
      - 8888:8080
    depends_on: 
      - mysql
    restart: always